// Curated currency list, not exhaustive ISO 4217 — major/most-used
// currencies first, then the rest alphabetically by code. Add more here
// if a store needs one that's missing rather than reverting to free text.
export const CURRENCY_OPTIONS = [
  { value: "USD", label: "USD — US Dollar" },
  { value: "EUR", label: "EUR — Euro" },
  { value: "GBP", label: "GBP — British Pound" },
  { value: "JPY", label: "JPY — Japanese Yen" },
  { value: "CHF", label: "CHF — Swiss Franc" },
  { value: "CAD", label: "CAD — Canadian Dollar" },
  { value: "AUD", label: "AUD — Australian Dollar" },
  { value: "CNY", label: "CNY — Chinese Yuan" },
  { value: "HKD", label: "HKD — Hong Kong Dollar" },
  { value: "SGD", label: "SGD — Singapore Dollar" },
  { value: "NZD", label: "NZD — New Zealand Dollar" },
  { value: "AED", label: "AED — UAE Dirham" },
  { value: "SAR", label: "SAR — Saudi Riyal" },
  { value: "INR", label: "INR — Indian Rupee" },
  { value: "KRW", label: "KRW — South Korean Won" },
  { value: "BRL", label: "BRL — Brazilian Real" },
  { value: "MXN", label: "MXN — Mexican Peso" },
  { value: "ZAR", label: "ZAR — South African Rand" },
  { value: "RUB", label: "RUB — Russian Ruble" },
  { value: "TRY", label: "TRY — Turkish Lira" },
  { value: "SEK", label: "SEK — Swedish Krona" },
  { value: "NOK", label: "NOK — Norwegian Krone" },
  { value: "DKK", label: "DKK — Danish Krone" },
  { value: "PLN", label: "PLN — Polish Zloty" },
  { value: "CZK", label: "CZK — Czech Koruna" },
  { value: "THB", label: "THB — Thai Baht" },
  { value: "IDR", label: "IDR — Indonesian Rupiah" },
  { value: "MYR", label: "MYR — Malaysian Ringgit" },
  { value: "PHP", label: "PHP — Philippine Peso" },
  { value: "ILS", label: "ILS — Israeli Shekel" },
];
